#pragma once

#define EXIT_OK 0
#define EXIT_DLL_LOAD_FAIL 1
#define EXIT_COMPOSITION_DISABLED 2
#define EXIT_A_EXEC_DID_NOT_RETURN 3
#define EXIT_PALETTE_OUT_OF_BOUNDS 4
#define EXIT_PALETTE_ADDED_TOO_MANY 5
