#pragma once

#define EXIT_OK 0
#define EXIT_DLL_LOAD_FAIL 1
#define EXIT_COMPOSITION_DISABLED 2
#define EXIT_A_EXEC_DID_NOT_RETURN 3
#define EXIT_TABLE_OUT_OF_BOUNDS 4
#define EXIT_TABLE_ADDED_TOO_MANY 5
#define EXIT_COULDNT_UPDATE_COLOR 6
#define EXIT_MULTIPLE_INSTANCES 7
#define EXIT_UNSUPPORTED_WINDOWS_VERSION 8

#define EXIT_SHOULD_NEVER_FAIL 255
