#############################################################################
# Makefile for building: ColorShifter-qt
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  ColorShifter-qt.pro
# Template: app
# Command: C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\bin\qmake.exe -o Makefile ColorShifter-qt.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: ColorShifter-qt.pro C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\win32-msvc2013\qmake.conf C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\spec_pre.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\common\shell-win32.conf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\qconfig.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_clucene_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_clucene_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_declarative.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_declarative_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_declarative.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_designer.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_designer_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_designer.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_designercomponents_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_help.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_help_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_help.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_multimedia.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_multimedia_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_platformsupport_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_qml.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_qml_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_qmldevtools_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_qmltest.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_qmltest_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_quick.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_quick_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_quickparticles_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_quickwidgets.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_quickwidgets_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_script.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_script_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_script.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_scripttools.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_scripttools_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_scripttools.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_uitools.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_uitools_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_xmlpatterns.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_xmlpatterns_private.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qdeclarativeview.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qgenericbearer.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qico.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qminimal.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qmldbg_inspector.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qmldbg_qtquick2.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qmldbg_tcp.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qmldbg_tcp_qtdeclarative.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qnativewifibearer.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qoffscreen.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qtaccessiblequick.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qtaccessiblewidgets.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qtaudio_windows.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qwindows.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_windowsprintersupport.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_lconvert.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_lrelease.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_lupdate.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qcollectiongenerator.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qdoc.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qhelpgenerator.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qlalr.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qml.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qml1plugindump.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qmlbundle.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qmlimportscanner.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qmlmin.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qmlprofiler.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qmltestrunner.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_syncqt.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_uic.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_xmlpatterns.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_xmlpatternsvalidator.pri \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\qt_functions.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\qt_config.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\win32\qt_config.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\win32-msvc2013\qmake.conf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\spec_post.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\exclusive_builds.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\default_pre.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\win32\default_pre.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\resolve_config.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\exclusive_builds_post.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\default_post.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\win32\rtti.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\precompile_header.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\warn_on.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\qt.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\resources.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\moc.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\win32\opengl.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\uic.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\win32\windows.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\testcase_targets.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\exceptions.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\yacc.prf \
		C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\lex.prf \
		ColorShifter-qt.pro \
		C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/lib/qtmain.prl \
		C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/lib/Qt5Core.prl \
		C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/lib/Qt5Widgets.prl \
		C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/lib/Qt5Gui.prl \
		C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/lib/libEGL.prl \
		C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/lib/libGLESv2.prl \
		C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/lib/translator.prl \
		C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/lib/preprocessor.prl \
		C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/plugins/accessible/qtaccessiblewidgets.prl \
		C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/plugins/platforms/qwindows.prl \
		C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/lib/Qt5PlatformSupport.prl \
		C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/plugins/imageformats/qico.prl
	$(QMAKE) -o Makefile ColorShifter-qt.pro
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\spec_pre.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\common\shell-win32.conf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\qconfig.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_clucene_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_clucene_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_core.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_declarative.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_declarative_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_declarative.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_designer.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_designer_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_designercomponents_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_help.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_help_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_help.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_multimedia.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_multimedia_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_network.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_platformsupport_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_qml.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_qml_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_qmldevtools_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_qmltest.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_qmltest_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_quick.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_quick_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_quickparticles_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_quickwidgets.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_quickwidgets_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_script.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_script_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_script.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_scripttools.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_scripttools_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_scripttools.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_uitools.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_uitools_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_xmlpatterns.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules-inst\qt_lib_xmlpatterns_private.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qdeclarativeview.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qgenericbearer.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qico.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qminimal.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qmldbg_inspector.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qmldbg_qtquick2.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qmldbg_tcp.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qmldbg_tcp_qtdeclarative.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qnativewifibearer.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qoffscreen.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qtaccessiblequick.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qtaccessiblewidgets.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qtaudio_windows.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_qwindows.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_plugin_windowsprintersupport.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_lconvert.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_lrelease.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_lupdate.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qcollectiongenerator.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qdoc.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qhelpgenerator.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qlalr.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qml.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qml1plugindump.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qmlbundle.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qmlimportscanner.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qmlmin.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qmlprofiler.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_qmltestrunner.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_syncqt.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_uic.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_xmlpatterns.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\modules\qt_tool_xmlpatternsvalidator.pri:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\qt_functions.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\qt_config.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\win32\qt_config.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\win32-msvc2013\qmake.conf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\spec_post.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\exclusive_builds.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\default_pre.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\win32\default_pre.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\resolve_config.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\default_post.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\win32\rtti.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\precompile_header.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\warn_on.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\qt.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\resources.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\moc.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\win32\opengl.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\uic.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\win32\windows.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\testcase_targets.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\exceptions.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\yacc.prf:
C:\Qt\Qt5.3.1-new\5.3\Src\qtbase\mkspecs\features\lex.prf:
ColorShifter-qt.pro:
C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/lib/qtmain.prl:
C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/lib/Qt5Core.prl:
C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/lib/Qt5Widgets.prl:
C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/lib/Qt5Gui.prl:
C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/lib/libEGL.prl:
C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/lib/libGLESv2.prl:
C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/lib/translator.prl:
C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/lib/preprocessor.prl:
C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/plugins/accessible/qtaccessiblewidgets.prl:
C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/plugins/platforms/qwindows.prl:
C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/lib/Qt5PlatformSupport.prl:
C:/Qt/Qt5.3.1-new/5.3/Src/qtbase/plugins/imageformats/qico.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ColorShifter-qt.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) C:\Users\ee\Documents\GitHub\ColorShifter-qt\colorshifter-qt_plugin_import.cpp

release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
